services:
  - type: web
    name: flask-user-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-user-db
          property: connectionString

databases:
  - name: flask-user-db